[package]
name = "rtop"
version = "0.1.0"
authors = ["Caleb Bassi <calebjbassi@gmail.com>"]
license = "MIT"
description = "A TUI system monitor written in Rust"
edition = "2018"

[dependencies]
chrono = "0.4.7"
crossbeam-channel = "0.3"
crossbeam-utils = "0.6.6"
crossterm = "0.9.6"
ctrlc = { version = "3.1.3", features = ["termination"] }
fern = "0.5.8"
hostname = "0.1.5"
lazy_static = "1.3.0"
log = "0.4.7"
num_cpus = "1.10.1"
num-rational = "0.2.2"
platform-dirs = "0.2.0"
psutil = "1.6.0"
serde = { version = "1.0.97", features = ["derive"] }
serde_json = "1.0.40"
size = "0.1.2"
structopt = "0.2.18"
tui = { version = "0.6.2", features = ["crossterm"] }
