[package]
name = "package-publisher"
version = "0.1.0"
authors = ["Caleb Bassi <calebjbassi@gmail.com>"]
edition = "2018"

[dependencies]
hex = "0.4.0"
reqwest = "0.10"
sha2 = "0.8.1"
tokio = { version = "0.2", features = ["full"] }
