name: Publish Binaries

on: release

jobs:
  publish:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macOS-latest
        target:
          - x86_64-unknown-linux-gnu
          - x86_64-apple-darwin
        exclude:
          - os: macOS-latest
            target: x86_64-unknown-linux-gnu
          - os: ubuntu-latest
            target: x86_64-apple-darwin
    steps:
      - name: Checkout sources
        uses: actions/checkout@v1

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true

      - name: Build release binary
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target=${{ matrix.target }}

      - name: Archive and compress binary
        run: tar -czf ytop-${{ github.event.release.tag_name }}-${{ matrix.target }}.tar.gz -C ./target/${{ matrix.target }}/release/ ytop

      - name: Upload archive to GitHub releases
        uses: JasonEtco/upload-to-release@master
        with:
          args: ytop-${{ github.event.release.tag_name }}-${{ matrix.target }}.tar.gz application/zip

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
