name: Release Binaries

on: release

env:
  NAME: rtop

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu
    steps:
      - name: Checkout sources
        uses: actions/checkout@v1

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true

      - name: Build release binary
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target=${{ matrix.target }}

      - name: Archive and compress binary
        run: tar -czf ${{ NAME }}-${{ GITHUB_REF }}-${{ matrix.target }}.tar.gz -C ./target/${{ matrix.target }}/release/ ${{ NAME }}

      - name: Upload archive to GitHub releases
        uses: JasonEtco/upload-to-release@master
        with:
          args: ${{ NAME }}-${{ GITHUB_REF }}-${{ matrix.target }}.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
